---
title: "Demostración de flujo de trabajo - Ruritania"
subtitle: "Taller de Evaluaciones RLE"
author:
  - name: "Tyler Erickson"
date: "2026-07-22"
execute:
  enabled: false
  freeze: false
  cache: false
lang: es
format:
  revealjs:
    theme: night
    css: styles.css
    slide-number: true
    navigation-mode: vertical
    # footer: "Taller de Evaluación RLE - Demostración de flujo de trabajo - Ruritania"
---

## Configuración de la Presentación {visibility="hidden"}

```{=html}
<style>
[data-class-output="small-output"] .cell-output table { font-size: 0.4em; }
</style>
```

In [2]:
#| include: false
# Create a directory for HTML map files
from pathlib import Path
Path('maps').mkdir(exist_ok=True)

## ¿Por qué Ruritania?

:::: {.columns}

::: {.column width="50%"}
**Ruritania** es un **país ficticio**, originalmente concebido como escenario para una trilogía de novelas de *Anthony Hope*, que comienza con *The Prisoner of Zenda (1894)*.

Hoy en día, el término se usa como nombre genérico para referirse a un país no especificado en discusiones académicas.
:::

::: {.column width="50%"}
![](https://upload.wikimedia.org/wikipedia/commons/5/53/Hope_Prisoner_of_Zenda_cover.jpg){fig-align="center" width="60%"}
:::

::::

::: {.notes}
<!-- en-source: auto-generated speaker notes, do not edit -->
**Why Ruritania?**

**Ruritania** is a **fictional country**, originally as a setting for a trilogy of novels by *Anthony Hope*, beginning with *The Prisoner of Zenda (1894)*.

Nowadays, the term is used as a placeholder name for an unspecified country in academic discussions.
:::

## Null Island

:::: {.columns}

::: {.column width="40%"}
Dado que necesitamos datos geoespaciales reales para demostrar los cálculos, y el país de Ruritania es ficticio, decidí usar una ubicación ficticia que suele emplearse en el contexto del software geoespacial.
:::

::: {.column width="50%"}
![](https://raw.githubusercontent.com/gnip/null-island/refs/heads/master/null_island_2013.svg){fig-align="center" width="60%" style="background-color: white; padding: 0.5em;"}

::: {style="text-align: center; font-size: 0.6em; opacity: 0.7;"}
fuente: [github.com/gnip/null-island](https://github.com/gnip/null-island)
:::
:::

::::

::: {.notes}
<!-- en-source: auto-generated speaker notes, do not edit -->
**Null Island**

Since we need actual geospatial data to demonstrate the calculations, and the country of Ruritania is a fictional, I decided to use a fictional location that is often used in the the context of geospatial software.

source: [github.com/gnip/null-island](https://github.com/gnip/null-island)
:::

## Descripción general de las herramientas

- `iucn-get-data` — [Datos de la Tipología Global de Ecosistemas (GET)](https://global-ecosystems.org/)
- `rle-python-gee` — Herramientas en Python para evaluaciones basadas en GEE
    - Basado en las [Publicaciones de la IUCN RLE](https://iucnrle.org/documents_and_publications)

::: {.notes}
<!-- en-source: auto-generated speaker notes, do not edit -->
**Tools Overview**

- `iucn-get-data` — [Global Ecosystem Typology (GET) data](https://global-ecosystems.org/)
- `rle-python-gee` — Python tools for GEE-based assessments
 - Based on [IUCN RLE Publications](https://iucnrle.org/documents_and_publications)
:::

# Tipología Global de Ecosistemas (GET)

##

::: {style="position: relative; display: inline-block;"}
![](images/rle_tools_overview.excalidraw.svg){fig-align="center" style="height: 80vh;"}

::: {.fragment style="position: absolute; left: 30%; top: 24%; width: 21%; height: 21%; border: 4px solid #ffcc00; border-radius: 6px; box-shadow: 0 0 0 9999px rgba(0,0,0,0.4);"}
:::

::: {.fragment style="position: absolute; left: 56%; top: 32%; width: 21%; height: 21%; border: 4px solid #ffcc00; border-radius: 6px; box-shadow: 0 0 0 9999px rgba(0,0,0,0.4);"}
:::

:::

::: {.notes}
<!-- en-source: auto-generated speaker notes, do not edit -->
**Global Ecosystem Typology (GET)**
:::

## Cargar la Tipología Global de Ecosistemas

::: {.notes}
<!-- en-source: auto-generated speaker notes, do not edit -->
**Load the Global Ecosystem Typology**
:::

In [3]:
#| echo: true
from iucn_get_data import Typology
from pprint import pprint

typology = Typology(language='spanish')
print(typology)

T: Terrestrial
  └─ T1: Bioma de bosques tropicales y subtropicales
      └─ T1.1: Tropical/Subtropical lowland rainforests
      └─ T1.2: Tropical/Subtropical dry forests and thickets
      └─ T1.3: Tropical/Subtropical montane rainforests
      └─ T1.4: Tropical heath forests
  └─ T2: Bioma de bosques templados y boreales
      └─ T2.1: Boreal and temperate high montane forests and woodlands
      └─ T2.2: Deciduous temperate forests
      └─ T2.3: Oceanic cool temperate rainforests
      └─ T2.4: Warm temperate laurophyll forests
      └─ T2.5: Temperate pyric humid forests
      └─ T2.6: Temperate pyric sclerophyll forests and woodlands
  └─ T3: Bioma de arbustales y matorrales
      └─ T3.1: Seasonally dry tropical shrublands
      └─ T3.2: Seasonally dry temperate heath and shrublands
      └─ T3.3: Cool temperate heathlands
      └─ T3.4: Young rocky pavements, lava flows and screes
  └─ T4: Bioma de sabanas y pastizales
      └─ T4.1: Trophic savannas
      └─ T4.2: Pyric tussock savannas
      └─ T4.3: Hummock savannas
      └─ T4.4: Temperate woodlands
      └─ T4.5: Temperate subhumid grasslands
  └─ T5: Bioma de desiertos y semidesiertos
      └─ T5.1: Semi-desert steppe
      └─ T5.2: Succulent or Thorny deserts and semi-deserts
      └─ T5.3: Sclerophyll hot deserts and semi-deserts
      └─ T5.4: Cool deserts and semi-deserts
      └─ T5.5: Hyper-arid deserts
  └─ T6: Bioma polar/alpino (criogénico)
      └─ T6.1: Ice sheets, glaciers and perennial snowfields
      └─ T6.2: Polar/alpine cliffs, screes, outcrops and lava flows
      └─ T6.3: Polar tundra and deserts
      └─ T6.4: Temperate alpine grasslands and shrublands
      └─ T6.5: Tropical alpine grasslands and herbfields
  └─ T7: Bioma de uso intensivo de la tierra
      └─ T7.1: Annual croplands
      └─ T7.2: Sown pastures and fields
      └─ T7.3: Plantations
      └─ T7.4: Urban and industrial ecosystems
      └─ T7.5: Derived semi-natural pastures and old fields
M: Marine
  └─ M1: Bioma de plataforma marina
      └─ M1.1: Seagrass meadows
      └─ M1.10: Rhodolith/Maërl beds
      └─ M1.2: Kelp forests
      └─ M1.3: Photic coral reefs
      └─ M1.4: Shellfish beds and reefs
      └─ M1.5: Photo-limited marine animal forests
      └─ M1.6: Subtidal rocky reefs
      └─ M1.7: Subtidal sand beds
      └─ M1.8: Subtidal mud plains
      └─ M1.9: Upwelling zones
  └─ M2: Bioma de aguas oceánicas pelágicas
      └─ M2.1: Epipelagic ocean waters
      └─ M2.2: Mesopelagic ocean water
      └─ M2.3: Bathypelagic ocean waters
      └─ M2.4: Abyssopelagic ocean waters
      └─ M2.5: Sea ice
  └─ M3: Bioma de los fondos marinos profundos
      └─ M3.1: Continental and island slopes
      └─ M3.2: Submarine canyons
      └─ M3.3: Abyssal plains
      └─ M3.4: Seamounts, ridges and plateaus
      └─ M3.5: Deepwater biogenic beds
      └─ M3.6: Hadal trenches and troughs
      └─ M3.7: Chemosynthetic-based-ecosystems (CBE)
  └─ M4: Bioma marino antropogénico
      └─ M4.1: Submerged artificial structures
      └─ M4.2: Marine aquafarms
F: Freshwater
  └─ F1: Bioma de ríos y arroyos
      └─ F1.1: Permanent upland streams
      └─ F1.2: Permanent lowland rivers
      └─ F1.3: Freeze-thaw rivers and streams
      └─ F1.4: Seasonal upland streams
      └─ F1.5: Seasonal lowland rivers
      └─ F1.6: Episodic arid rivers
      └─ F1.7: Large lowland rivers
  └─ F2: Bioma de lagos
      └─ F2.1: Large permanent freshwater lakes
      └─ F2.10: Subglacial lakes
      └─ F2.2: Small permanent freshwater lakes
      └─ F2.3: Seasonal freshwater lakes
      └─ F2.4: Freeze-thaw freshwater lakes
      └─ F2.5: Ephemeral freshwater lakes
      └─ F2.6: Permanent salt and soda lakes
      └─ F2.7: Ephemeral salt lakes
      └─ F2.8: Artesian springs and oases
      └─ F2.9: Geothermal pools and wetlands
  └─ F3: Bioma de humedales artificiales
      └─ F3.1: Large reservoirs
      └─ F3.2: Constructed lacustrine wetlands
      └─ F3.3: Rice paddies
      └─ F3.4: Freshwater aquafarms
      └─ F3.5: Canals, ditches and drains
S: Subterranean
  └─ S1: Bioma lítico subterráneo
      └─ S1.1: Aerobic caves
      └─ S1.2: Endolithic systems
  └─ S2: Bioma de espacios subterráneos antropogénicos
      └─ S2.1: Anthropogenic subterranean voids
MT: Marine-Terrestrial
  └─ MT1: Bioma de las costas
      └─ MT1.1: Rocky Shorelines
      └─ MT1.2: Muddy Shorelines
      └─ MT1.3: Sandy Shorelines
      └─ MT1.4: Boulder and cobble shores
  └─ MT2: Bioma costero supralitoral
      └─ MT2.1: Coastal shrublands and grasslands
      └─ MT2.2: Large seabird and pinniped colonies
  └─ MT3: Bioma de costas antropogénicas
      └─ MT3.1: Artificial shorelines
SF: Subterranean-Freshwater
  └─ SF1: Bioma de aguas dulces subterráneas
      └─ SF1.1: Underground streams and pools
      └─ SF1.2: Groundwater ecosystems
  └─ SF2: Bioma de aguas dulces subterráneas antropogénicas
      └─ SF2.1: Water pipes and subterranean canals
      └─ SF2.2: Flooded mines and other voids
FM: Freshwater-Marine
  └─ FM1: Bioma de aguas de transición semiconfinadas
      └─ FM1.1: Deepwater coastal inlets
      └─ FM1.2: Permanently open riverine estuaries and bays
      └─ FM1.3: Intermittently closed and open lakes and lagoons
MFT: Marine-Terrestrial-Freshwater
  └─ MFT1: Bioma de mareas salobres
      └─ MFT1.1: Coastal river deltas
      └─ MFT1.2: Intertidal forests and shrublands
      └─ MFT1.3: Coastal saltmarshes and reedbeds
SM: Subterranean-Marine
  └─ SM1: Bioma subterráneo mareal
      └─ SM1.1: Anchialine caves
      └─ SM1.2: Anchialine pools
      └─ SM1.3: Sea caves
TF: Terrestrial-Freshwater
  └─ TF1: Bioma de humedales palustres
      └─ TF1.1: Tropical flooded forests and peat forests
      └─ TF1.2: Subtropical/temperate forested wetlands
      └─ TF1.3: Permanent marshes
      └─ TF1.4: Seasonal floodplain marshes
      └─ TF1.5: Episodic arid floodplains
      └─ TF1.6: Boreal, temperate and montane peat bogs
      └─ TF1.7: Boreal and temperate fens
A: Atmospheric

## Ejemplo: Obtener Biomas del Reino Terrestre

::: scrollbox

::: {.notes}
<!-- en-source: auto-generated speaker notes, do not edit -->
**Example: Get Terrestrial Realm Biomes**
:::

In [4]:
#| echo: true
from iucn_get_data import get_biomes, get_groups
from pprint import pprint

pprint(get_biomes(realm='T'))

{'T1': Biome(code='T1',
             name='Tropical-subtropical forests',
             description='The Tropical-subtropical forests biome includes '
                         'moderate to highly productive ecosystems with closed '
                         'tree canopies occurring at lower latitudes north and '
                         'south of the equator. Fragmented occurrences extend '
                         'to the subtropics in suitable mesoclimates.\n'
                         'High primary productivity is underpinned by high '
                         'insolation, warm temperatures, relatively low '
                         'seasonal variation in day length and temperature '
                         '(increasing to the subtropics), and strong water '
                         'surpluses associated with the intertropical '
                         'convergence zone extending to wetter parts of the '
                         'seasonal tropics and subtropics. Productivity and '
                         'biomass vary in response to: i) strong rainfall '
                         'gradients associated with seasonal migration of the '
                         'intertropical convergence zone, ii) altitudinal '
                         'gradients in precipitation, cloud cover, and '
                         'temperatures, and iii) edaphic gradients that '
                         'influence the availability of soil nutrients.\n'
                         'Species diversity and the complexity of both '
                         'vegetation and trophic structures are positively '
                         'correlated with standing biomass and primary '
                         'productivity, however, trophic webs and other '
                         'ecosystem processes are strongly regulated from the '
                         'bottom-up by the dominant photoautotrophs (trees), '
                         'which fix abundant energy and carbon, engineer '
                         'habitats for many other organisms, and underpin '
                         'feedbacks related to nutrient and water cycling and '
                         'regional climate.\n'
                         'Complex nutrient cycling and/or sequestering '
                         'mechanisms are common, countering the high potential '
                         'for soil nutrient leaching due to high rainfall. '
                         'Plant species exhibit leaf plasticity, shade '
                         'tolerance, and gap-phase dynamics in response to the '
                         'periodic opening of canopy gaps initiated by tree '
                         'death, storm damage, and lightning strikes. Fires '
                         'may occur in ecotonal areas between these forests '
                         'and savannas.\n'
                         'Biogeographic legacies result in strong '
                         'compositional distinctions and consequently some '
                         'functional differences among land masses within the '
                         'biome',
             url='https://global-ecosystems.org/explore/biomes/T1',
             functional_groups={'T1.1': FunctionalGroup(code='T1.1',
                                                        name='Tropical/Subtropical '
                                                             'lowland '
                                                             'rainforests',
                                                        description='A huge '
                                                                    'diversity '
                                                                    'of '
                                                                    'species '
                                                                    'occupy '
                                                                    'niches '
                                                                    'within a '
                                                                    'complex '
                                                                    'vertically-layered '
                                                                    'structure '
                                                                    'of plant '
                                                                    'forms. '
                                                                    'High '
                                                                    'productivity '
                                                                    'is '
                                                                    'fuelled '
                                                                    'by '
                                                                    'rapid-growing '
                                                                    'plants '
                                                                    'including '
                                                                    'buttressed '
                                                                    'trees, '
                                                                    'bamboos, '
                                                                    'epiphytes, '
                                                                    'lianas '
                                                                    'and '
                                                                    'ferns. '
                                                                    'Forest '
                                                                    'canopies '
                                                                    'sustain '
                                                                    'moist '
                                                                    'soils and '
                                                                    'abundant '
                                                                    'leaf '
                                                                    'litter '
                                                                    'decomposed '
                                                                    'by fungi '
                                                                    'and '
                                                                    'bacteria. '
                                                                    'High '
                                                                    'diversity '
                                                                    'of '
                                                                    'invertebrates '
                                                                    'at all '
                                                                    'levels of '
                                                                    'the '
                                                                    'forest '
                                                                    'supports '
                                                                    'diverse '
                                                                    'vertebrate '
                                                                    'life '
                                                                    'forms, '
                                                                    'particularly '
                                                                    'mammals '
                                                                    'and '
                                                                    'birds, '
                                                                    'which '
                                                                    'play '
                                                                    'critical '
                                                                    'roles in '
                                                                    'plant '
                                                                    'dispersal '
                                                                    'and '
                                                                    'pollination. '
                                                                    'Conditions '
                                                                    'near the '
                                                                    'equator '
                                                                    'are '
                                                                    'stable '
                                                                    'and humid '
                                                                    'year-round '
                                                                    '(up to '
                                                                    '6000 mm '
                                                                    'rain per '
                                                                    'annum), '
                                                                    'but '
                                                                    'become '
                                                                    'more '
                                                                    'seasonal '
                                                                    'with mild '
                                                                    'winter '
                                                                    'frosts in '
                                                                    'the '
                                                                    'subtropics.',
                                                        url='https://global-ecosystems.org/explore/groups/T1.1',
                                                        biome_code='T1',
                                                        realm_code='T'),
                                'T1.2': FunctionalGroup(code='T1.2',
                                                        name='Tropical/Subtropical '
                                                             'dry forests and '
                                                             'thickets',
                                                        description='Tropical-subtropical '
                                                                    'dry '
                                                                    'forests '
                                                                    'and '
                                                                    'thickets '
                                                                    'are '
                                                                    'characterised '
                                                                    'by '
                                                                    'fertile '
                                                                    'substrates '
                                                                    'and '
                                                                    'seasonally '
                                                                    'dry '
                                                                    'conditions '
                                                                    '(~1800 mm '
                                                                    'per year, '
                                                                    'with a '
                                                                    'period of '
                                                                    '3 to 6 '
                                                                    'months '
                                                                    'receiving '
                                                                    'less than '
                                                                    '100 mm '
                                                                    'per '
                                                                    'month) '
                                                                    'that '
                                                                    'drive '
                                                                    'markedly '
                                                                    'seasonal '
                                                                    'patterns '
                                                                    'of '
                                                                    'productivity. '
                                                                    'Tree-diversity '
                                                                    'is high, '
                                                                    'with a '
                                                                    'variable '
                                                                    'mixture '
                                                                    'of '
                                                                    'evergreen '
                                                                    'and '
                                                                    'drought-deciduous '
                                                                    'trees, '
                                                                    'with '
                                                                    'abundant '
                                                                    'vines, '
                                                                    'but fewer '
                                                                    'epiphytes, '
                                                                    'ferns, '
                                                                    'mosses, '
                                                                    'and '
                                                                    'forbs, '
                                                                    'limited '
                                                                    'by '
                                                                    'seasonal '
                                                                    'drought. '
                                                                    'Abundant '
                                                                    'leaf '
                                                                    'litter is '
                                                                    'decomposed '
                                                                    'by fungi '
                                                                    'and '
                                                                    'microbes '
                                                                    'within '
                                                                    'complex '
                                                                    'foodwebs '
                                                                    'dominated '
                                                                    'by '
                                                                    'vertebrates '
                                                                    'of all '
                                                                    'kinds.',
                                                        url='https://global-ecosystems.org/explore/groups/T1.2',
                                                        biome_code='T1',
                                                        realm_code='T'),
                                'T1.3': FunctionalGroup(code='T1.3',
                                                        name='Tropical/Subtropical '
                                                             'montane '
                                                             'rainforests',
                                                        description='These '
                                                                    'mountain '
                                                                    'rainforests '
                                                                    'are '
                                                                    'characterised '
                                                                    'by a '
                                                                    'single-layered '
                                                                    'tree '
                                                                    'canopy, '
                                                                    'with '
                                                                    'epiphytic '
                                                                    'ferns, '
                                                                    'bryophytes, '
                                                                    'lichens, '
                                                                    'orchids, '
                                                                    'and '
                                                                    'bromeliads '
                                                                    'draping '
                                                                    'tree '
                                                                    'branches. '
                                                                    'Grasses '
                                                                    'are rare '
                                                                    'or '
                                                                    'absent. '
                                                                    'At high '
                                                                    'altitude '
                                                                    'forest '
                                                                    'structure '
                                                                    'becomes '
                                                                    'less '
                                                                    'complex, '
                                                                    'with '
                                                                    'dwarf '
                                                                    'tree '
                                                                    'forms. '
                                                                    'Although '
                                                                    'rainfall '
                                                                    'is '
                                                                    'abundant '
                                                                    '(up to '

:::

## Ejemplo: Obtener los Grupos Funcionales del Reino Terrestre

::: {.scrollbox}

::: {.notes}
<!-- en-source: auto-generated speaker notes, do not edit -->
**Example: Get Terrestrial Realm Functional Groups**
:::

In [5]:
#| echo: true
[f'{v.code}: {v.name}' for k, v in get_groups(realm='T').items()]

['T1.1: Tropical/Subtropical lowland rainforests',
 'T1.2: Tropical/Subtropical dry forests and thickets',
 'T1.3: Tropical/Subtropical montane rainforests',
 'T1.4: Tropical heath forests',
 'T2.1: Boreal and temperate high montane forests and woodlands',
 'T2.2: Deciduous temperate forests',
 'T2.3: Oceanic cool temperate rainforests',
 'T2.4: Warm temperate laurophyll forests',
 'T2.5: Temperate pyric humid forests',
 'T2.6: Temperate pyric sclerophyll forests and woodlands',
 'T3.1: Seasonally dry tropical shrublands',
 'T3.2: Seasonally dry temperate heath and shrublands',
 'T3.3: Cool temperate heathlands',
 'T3.4: Young rocky pavements, lava flows and screes',
 'T4.1: Trophic savannas',
 'T4.2: Pyric tussock savannas',
 'T4.3: Hummock savannas',
 'T4.4: Temperate woodlands',
 'T4.5: Temperate subhumid grasslands',
 'T5.1: Semi-desert steppe',
 'T5.2: Succulent or Thorny deserts and semi-deserts',
 'T5.3: Sclerophyll hot deserts and semi-deserts',
 'T5.4: Cool deserts and semi-deserts',
 'T5.5: Hyper-arid deserts',
 'T6.1: Ice sheets, glaciers and perennial snowfields',
 'T6.2: Polar/alpine cliffs, screes, outcrops and lava flows',
 'T6.3: Polar tundra and deserts',
 'T6.4: Temperate alpine grasslands and shrublands',
 'T6.5: Tropical alpine grasslands and herbfields',
 'T7.1: Annual croplands',
 'T7.2: Sown pastures and fields',
 'T7.3: Plantations',
 'T7.4: Urban and industrial ecosystems',
 'T7.5: Derived semi-natural pastures and old fields']

:::

## Navegar

::: {.notes}
<!-- en-source: auto-generated speaker notes, do not edit -->
**Navigate**
:::

In [6]:
#| echo: true
# Select by realm / biome / functional group
pprint(typology.realms['T'].biomes['T1'].functional_groups['T1.3'])

FunctionalGroup(code='T1.3',
                name='Tropical/Subtropical montane rainforests',
                description='These mountain rainforests are characterised by a '
                            'single-layered tree canopy, with epiphytic ferns, '
                            'bryophytes, lichens, orchids, and bromeliads '
                            'draping tree branches. Grasses are rare or '
                            'absent. At high altitude forest structure becomes '
                            'less complex, with dwarf tree forms. Although '
                            'rainfall is abundant (up to 6000 mm per year), '
                            'productivity is limited by cool temperatures, '
                            'wind exposure and shallow soils, although under '
                            'the canopy a moist shady microclimate provides '
                            'stable habitat for a frog, bird, plant and '
                            'invertebrate species that are found nowhere else.',
                url='https://global-ecosystems.org/explore/groups/T1.3',
                biome_code='T1',
                realm_code='T')

# Cargando los Datos Geoespaciales

::: {.notes}
<!-- en-source: auto-generated speaker notes, do not edit -->
**Loading the Geospatial Data**
:::

##

::: {style="position: relative; display: inline-block;"}
![](images/rle_tools_overview.excalidraw.svg){fig-align="center" style="height: 80vh;"}

::: {.fragment style="position: absolute; left: 30%; top: 45%; width: 21%; height: 21%; border: 4px solid #ffcc00; border-radius: 6px; box-shadow: 0 0 0 9999px rgba(0,0,0,0.4);"}
:::

::: {.fragment style="position: absolute; left: 56%; top: 32%; width: 21%; height: 21%; border: 4px solid #ffcc00; border-radius: 6px; box-shadow: 0 0 0 9999px rgba(0,0,0,0.4);"}
:::

:::

## Cargar los polígonos de ecosistemas

::: scrollbox

::: {.notes}
<!-- en-source: auto-generated speaker notes, do not edit -->
**Load the ecosystem polygons**
:::

In [7]:
#| echo: false
import urllib.request
from pathlib import Path

data_path = Path('data/ruritania_ecosystems.shp.zip')

# If the data doesn't exist locally, download it.
if not data_path.exists():
    data_path.parent.mkdir(parents=True, exist_ok=True)
    urllib.request.urlretrieve(
        'https://storage.googleapis.com/rle_test_data/null_island.shp.zip',
        data_path
    )

In [8]:
#| echo: true
from pathlib import Path
from rle.core import Ecosystems

country_name = 'ruritania'
data_path = Path(f'data/{country_name}_ecosystems.shp.zip')
ecosystems = Ecosystems.from_file(
    data_path,
    ecosystem_column='ECO_CODE',
    ecosystem_name_column='ECO_NAME',
    functional_group_column='EFG1'
)
ecosystems

EcosystemsFile(data=PosixPath('data/ruritania_ecosystems.shp.zip'))

In [9]:
#| echo: true
ecosystems.head()

,id,COD,ECO_NAME,EFG1,Glob_Typol,ECO_CODE,geometry
0,00000000000000000000,D01,Null Island Tropical Forest,T1.1,T1.1_NullIsland_forest_D01,T1.1.1,"POLYGON ((-0.02268 0.02599, -0.01316 0.02599, ..."
1,00000000000000000001,D03,Null Island Alpine Grassland,T6.5,T6.5_NullIsland_alpine_D03,T6.5.1,"POLYGON ((0.008 0.012, 0.016 0.015, 0.023 0.01..."
2,00000000000000000002,D02,Null Island Marine Shelf,M1.1,M1.1_NullIsland_marine_shelf_D02,M1.1.1,"POLYGON ((-0.06 -0.05, -0.06 0.05, 0.06 0.05, ..."

In [10]:
#| echo: true
ecosystems.unique_ecosystems()

['M1.1.1', 'T1.1.1', 'T6.5.1']

In [11]:
#| echo: true
ecosystems.unique_functional_groups()

['M1.1', 'T1.1', 'T6.5']

:::

## Mapa Interactivo de Ecosistemas

::: {.notes}
<!-- en-source: auto-generated speaker notes, do not edit -->
**Ecosystems Interactive Map**
:::

In [12]:
#| echo: true
#| output: false
ecosystems.to_map()

VBox(children=(<lonboard._map.Map object at 0x30f8a8050>, VBox(children=(ErrorOutput(), ErrorOutput(), ErrorOu…

In [13]:
#| include: false
# Regenerate the standalone map HTML for the slide iframe.
# Hidden from the rendered slide; runs only when this notebook is
# executed in JupyterLab.
ecosystems.to_map().to_html(f'maps/{country_name}_ecosystems.html')

In [14]:
#| echo: false
from IPython.display import HTML, display
display(HTML(
    f'<div class="r-stretch"><iframe src="maps/{country_name}_ecosystems.html" '
    f'style="display: block; width: 90%; height: 100%; margin: 0 auto; '
    f'border: 1px solid #444; border-radius: 4px;" loading="lazy"></iframe></div>'
))

# Seleccionar un Solo Ecosistema

::: {.notes}
<!-- en-source: auto-generated speaker notes, do not edit -->
**Select a Single Ecosystem**
:::

In [15]:
#| echo: true
# Filter ecosystems then display
ecosystem_code = 'T1.1.1'
ecosystem = ecosystems.filter(ecosystem_code)
print(f'{ecosystem.size()=}')

ecosystem.size()=1

In [16]:
#| echo: true
#| output: false
ecosystem.to_map()

VBox(children=(<lonboard._map.Map object at 0x30f8a5e50>, VBox(children=(ErrorOutput(), ErrorOutput(), ErrorOu…

In [17]:
#| include: false
# Regenerate the standalone map HTML for the slide iframe.
# Hidden from the rendered slide; runs only when this notebook is
# executed in JupyterLab.
ecosystem.to_map().to_html(f'maps/{country_name}_{ecosystem_code}.html')

In [18]:
#| echo: false
from IPython.display import HTML, display
display(HTML(
    f'<div class="r-stretch"><iframe src="maps/{country_name}_{ecosystem_code}.html" '
    f'style="display: block; width: 90%; height: 100%; margin: 0 auto; '
    f'border: 1px solid #444; border-radius: 4px;" loading="lazy"></iframe></div>'
))

# Extensión de la ocurrencia (EOO)

> **Extensión de la ocurrencia (EOO).** La EOO de un ecosistema es el área (km2) de un polígono convexo mínimo – el polígono más pequeño en el que ningún ángulo interno supera los 180° y que abarca todas las ocurrencias espaciales actuales conocidas del tipo de ecosistema. 
> 
> El polígono convexo mínimo (también conocido como envolvente convexa) no debe excluir ninguna área, discontinuidad o disyunción, independientemente de si el ecosistema puede ocurrir o no en esas áreas. Regiones como océanos (para ecosistemas terrestres), tierra firme (para ecosistemas costeros o marinos), o áreas fuera del área de estudio (como en un país diferente) deben permanecer incluidas dentro del polígono convexo mínimo para garantizar que este método estandarizado sea comparable entre tipos de ecosistemas. Además, estas características contribuyen a distribuir los riesgos a lo largo de la distribución del ecosistema, al hacer que las diferentes partes de su distribución sean más independientes espacialmente.

::: {.notes}
<!-- en-source: auto-generated speaker notes, do not edit -->
**Extent of occurrence (EOO)**

> **Extent of occurrence (EOO).** The EOO of an ecosystem is the area (km2) of a minimum convex polygon – the smallest polygon in which no internal angle exceeds 180° that encompasses all known current spatial occurrences of the ecosystem type.
>
> The minimum convex polygon (also known as a convex hull) must not exclude any areas, discontinuities or disjunctions, regardless of whether the ecosystem can occur in those areas or not. Regions such as oceans (for terrestrial ecosystems), land (for coastal or marine ecosystems), or areas outside the study area (such as in a different country) must remain included within the minimum convex polygon to ensure that this standardised method is comparable across ecosystem types. In addition, these features contribute to spreading risks across the distribution of the ecosystem by making different parts of its distribution more spatially independent.
:::

## Calcular EOO

::: {.notes}
<!-- en-source: auto-generated speaker notes, do not edit -->
**Calculate EOO**
:::

In [19]:
#| echo: true
#| output: false
from lonboard import Map
from rle.core.eoo import make_eoo

eoo = make_eoo(ecosystem).compute()
display(Map(layers=eoo.to_layer() + ecosystem.to_layer()))

VBox(children=(<lonboard._map.Map object at 0x30f8b6650>, VBox(children=(ErrorOutput(), ErrorOutput(), ErrorOu…

In [20]:
#| include: false
# Regenerate the standalone map HTML for the slide iframe.
# Hidden from the rendered slide; runs only when this notebook is
# executed in JupyterLab.
Map(layers=eoo.to_layer() + ecosystem.to_layer()).to_html(f'maps/{country_name}_{ecosystem_code}_eoo.html')

In [21]:
#| echo: false
from IPython.display import HTML, display
display(HTML(
    f'<div class="r-stretch"><iframe src="maps/{country_name}_{ecosystem_code}_eoo.html" '
    f'style="display: block; width: 90%; height: 100%; margin: 0 auto; '
    f'border: 1px solid #444; border-radius: 4px;" loading="lazy"></iframe></div>'
))

In [22]:
#| echo: true
print(f'EOO is {eoo.area_km2:.1f} km2')

EOO is 73.2 km2

# Área de ocupación (AOO)

::: {.notes}
<!-- en-source: auto-generated speaker notes, do not edit -->
**Area of occupancy (AOO)**
:::

::: {.scrollbox}

> **Área de ocupación (AOO). La AOO de un ecosistema definido en la RLE se determina contando el número de celdas de una cuadrícula de 10 × 10 km^2^ que contienen el tipo de ecosistema.**

> Las estimaciones de la extensión del ecosistema son altamente sensibles al tamaño de grano (resolución espacial) de los mapas fuente (Nicholson et al., 2009), por lo que todas las medidas de AOO de un tipo de ecosistema deben estandarizarse a un tamaño de grano espacial común (Keith et al., 2018). Este tamaño de grano relativamente grande se aplica por cuatro razones:
>
> (i) los límites de los ecosistemas son inherentemente vagos (Regan et al., 2002), por lo que es más fácil determinar que una ocurrencia de un ecosistema se encuentra dentro de una celda de cuadrícula más grande que en una más pequeña;
> (ii) pueden requerirse celdas más grandes para diagnosticar la presencia de ecosistemas caracterizados por procesos que operan a grandes escalas espaciales, o que poseen rasgos diagnósticos escasos, crípticos, agrupados o móviles (por ejemplo, sistemas pelágicos o artesianos);
> (iii) las celdas más grandes permiten estimar la AOO incluso cuando los datos de distribución de alta resolución son limitados; y
> (iv) los estudios de simulación han indicado que las celdas más grandes predicen mejor el riesgo frente a eventos de amenaza del mundo real que las celdas de escala más fina (Keith et al., 2018). Un conjunto de datos global en cuadrícula de 10 × 10 km adecuado para este propósito está disponible a través de un repositorio de datos público en formatos raster y vectorial (Murray, 2017).

> Algunas distribuciones de ecosistemas presentan una distribución de tamaños de parche muy sesgada. En estos casos, un gran número de parches pequeños contribuye con un efecto de dispersión de riesgo insignificante en comparación con el de los parches más grandes. Por lo tanto, los evaluadores deben aplicar una corrección excluyendo de la AOO aquellas celdas de la cuadrícula que, en conjunto, contienen parches del tipo de ecosistema que representan menos del 1% del área total mapeada del tipo de ecosistema, incluyendo así siempre el 99% de la extensión del ecosistema.
>
> El protocolo para este ajuste incluye los siguientes pasos:
>
>   (1) Intersectar la cuadrícula de AOO con el mapa de distribución del ecosistema.
>   (2) Calcular la extensión del tipo de ecosistema en cada celda de la cuadrícula ('área') y sumar estas áreas para obtener el área total del ecosistema ('área total').
>   (3) Ordenar las celdas de la cuadrícula en orden ascendente según su área (las más pequeñas primero). Calcular la suma acumulada del área por celda ('área acumulada').
>   (4) Calcular la 'proporción acumulada' dividiendo el 'área acumulada' entre el 'área total' (la proporción acumulada toma valores entre 0 y 1).
>   (5) Calcular la AOO contando el número de celdas con una 'proporción acumulada' mayor a 0.01 (es decir, excluir las celdas que en conjunto representan hasta el 1% de la extensión total mapeada del tipo de ecosistema).

:::

::: {.notes}
<!-- en-source: auto-generated speaker notes, do not edit -->
> **Area of occupancy (AOO). The AOO of an ecosystem defined in the RLE is determined by counting the number of 10 × 10 km^2^ grid cells that contain the ecosystem type.**

> Estimates of ecosystem extent are highly sensitive to the grain size (spatial resolution) of source maps (Nicholson et al., 2009), so all measures of AOO of an ecosystem type must be standardised to a common spatial grain (Keith et al., 2018). This relatively large grain size is applied for four reasons:
>
> (i) ecosystem boundaries are inherently vague (Regan et al., 2002), so it is easier to determine that an ecosystem occurrence falls within a larger grid cell than a smaller one;
> (ii) larger cells may be required to diagnose the presence of ecosystems characterised by processes that operate over large spatial scales, or possess diagnostic features that are sparse, cryptic, clustered or mobile (e.g. pelagic or artesian systems);
> (iii) larger cells allow AOO estimation even when high resolution distribution data are limited; and
> (iv) simulation studies have indicated that larger cells better predict risk in the face of real-world threat events than finer scale cells (Keith et al., 2018). A global 10 × 10 km gridded dataset suitable for this purpose is available via a public data repository in raster and vector formats (Murray, 2017).
>
> Some ecosystem distributions comprise a highly skewed distribution of patch sizes. In these cases, large numbers of small patches contribute a negligible risk-spreading effect compared to that of larger patches. Assessors should therefore apply a correction by excluding from the AOO those grid cells that, collectively, contain patches of the ecosystem type that account for less than 1% of the total mapped area of the ecosystem type, thus always including 99% of the ecosystem extent.
>
> The protocol for this adjustment includes the following steps:
>
> (1) Intersect AOO grid with the ecosystem’s distribution map.
> (2) Calculate extent of the ecosystem type in each grid cell (‘area’) and sum these areas to obtain the total ecosystem area (‘total area’).
> (3) Arrange grid cells in ascending order based on their area (smaller first). Calculate accumulated sum of area per cell (‘cumulative area’).
> (4) Calculate ‘cumulative proportion’ by dividing ‘cumulative area’ by ‘total area’ (cumulative proportion takes values between 0 and 1)
> (5) Calculate AOO by counting the number of cells with a ‘cumulative proportion’ greater than 0.01 (i.e. exclude cells that in combination account for up to 1% of the total mapped extent of the ecosystem type).
:::

## AOO Grid

(1) Intersectar la grilla AOO con el mapa de distribución del ecosistema.
(2) Calcular la extensión del tipo de ecosistema en cada celda de la grilla (‘área’) y sumar estas áreas para obtener el área total del ecosistema (‘área total’).

::: {.notes}
<!-- en-source: auto-generated speaker notes, do not edit -->
**AOO Grid**

(1) Intersect AOO grid with the ecosystem’s distribution map.
(2) Calculate extent of the ecosystem type in each grid cell (‘area’) and sum these areas to obtain the total ecosystem area (‘total area’).
:::

In [23]:
#| echo: true
#| output: false
from rle.core.aoo import make_aoo_grid

aoo_grid = make_aoo_grid(ecosystems).compute()

display(
    Map(layers=aoo_grid.to_layer() + ecosystems.to_layer())
)

VBox(children=(<lonboard._map.Map object at 0x30f863790>, VBox(children=(ErrorOutput(), ErrorOutput(), ErrorOu…

In [24]:
#| include: false
# Regenerate the standalone map HTML for the slide iframe.
# Hidden from the rendered slide; runs only when this notebook is
# executed in JupyterLab.
Map(layers=aoo_grid.to_layer() + ecosystems.to_layer()).to_html(f'maps/{country_name}_aoo_grid.html')

In [25]:
#| echo: false
from IPython.display import HTML, display
display(HTML(
    f'<div class="r-stretch"><iframe src="maps/{country_name}_aoo_grid.html" '
    f'style="display: block; width: 90%; height: 100%; margin: 0 auto; '
    f'border: 1px solid #444; border-radius: 4px;" loading="lazy"></iframe></div>'
))

## Celdas de la Cuadrícula

::: {.notes}
<!-- en-source: auto-generated speaker notes, do not edit -->
**Grid Cells**
:::

In [26]:
#| echo: true
aoo_grid.grid_cells.head()

,grid_col,grid_row,geometry,count_geoms,count_ecosystems,M1_1_1,T1_1_1,T6_5_1
0,-1,-1,"POLYGON ((0 -0.09044, 0 0, -0.08983 0, -0.0898...",2,2,0.230587,0.138685,0.000000
1,-1,0,"POLYGON ((0 0, 0 0.09044, -0.08983 0.09044, -0...",2,2,0.219648,0.149624,0.000000
2,0,-1,"POLYGON ((0.08983 -0.09044, 0.08983 0, 0 0, 0 ...",3,3,0.193924,0.164326,0.011022
3,0,0,"POLYGON ((0.08983 0, 0.08983 0.09044, 0 0.0904...",3,3,0.195383,0.143245,0.030645

Filtrar a un solo ecosistema.

::: {.notes}
<!-- en-source: auto-generated speaker notes, do not edit -->
Filter to a single ecosystem.
:::

In [27]:
#| echo: true
aoo_grid_filtered = aoo_grid.filter_by_ecosystem(ecosystem_code)

## Visualizar Variaciones de Área

Visualiza la variación en la cobertura de área fraccionaria del ecosistema en cada cuadrícula de AOO.

::: {.notes}
<!-- en-source: auto-generated speaker notes, do not edit -->
**Visualize Area Variations**

Visualize variation in the ecosystem's fractional area coverage of each AOO grid.
:::

In [28]:
#| echo: true
from matplotlib.colors import LinearSegmentedColormap
from lonboard.colormap import apply_continuous_cmap
from rle.core.aoo import slugify_ecosystem_name

ecosystem_column = slugify_ecosystem_name(ecosystem_code)

cmap = LinearSegmentedColormap.from_list("white_red", ["white", "red"])
values = aoo_grid_filtered.grid_cells[ecosystem_column].values
normalized = (values - values.min()) / (values.max() - values.min())
colors = apply_continuous_cmap(normalized, cmap)

Map(
    layers=aoo_grid_filtered.to_layer(get_fill_color=colors) 
    + ecosystems.to_layer()
    + ecosystem.to_layer()
)

VBox(children=(<lonboard._map.Map object at 0x3149cf150>, VBox(children=(ErrorOutput(), ErrorOutput(), ErrorOu…

```
## AOO Calculation Steps

::: {.scrollbox}
```

::: {.notes}
<!-- en-source: auto-generated speaker notes, do not edit -->
**AOO Calculation Steps**
:::

In [29]:
#| echo: true
keep = ['geometry', 'grid_col', 'grid_row', ecosystem_column]
gdf = aoo_grid_filtered.grid_cells[keep].sort_values(by=ecosystem_column)   # <3>
gdf["cumulative_area"] = gdf[ecosystem_column].cumsum()
total_area = gdf["cumulative_area"].iloc[-1]                                # <4>
gdf["cumulative_proportion"] = gdf["cumulative_area"] / total_area          # <4>
display(gdf)

aoo = len(gdf[gdf["cumulative_proportion"] > 0.01])   # <5>
print(f'AOO is {aoo} cells')

,geometry,grid_col,grid_row,T1_1_1,cumulative_area,cumulative_proportion
0,"POLYGON ((0 -0.09044, 0 0, -0.08983 0, -0.0898...",-1,-1,0.138685,0.138685,0.232740
3,"POLYGON ((0.08983 0, 0.08983 0.09044, 0 0.0904...",0,0,0.143245,0.281929,0.473132
1,"POLYGON ((0 0, 0 0.09044, -0.08983 0.09044, -0...",-1,0,0.149624,0.431553,0.724230
2,"POLYGON ((0.08983 -0.09044, 0.08983 0, 0 0, 0 ...",0,-1,0.164326,0.595879,1.000000

AOO is 4 cells

3. Ordenar las celdas de la cuadrícula en orden ascendente según su área (la más pequeña primero). Calcular la suma acumulada del área por celda ('área acumulada').
4. Calcular la 'proporción acumulada' dividiendo el 'área acumulada' entre el 'área total' (la proporción acumulada toma valores entre 0 y 1).
5. Calcular el AOO contando el número de celdas con una 'proporción acumulada' mayor a 0.01 (es decir, excluir las celdas que en conjunto representan hasta el 1% de la extensión total mapeada del tipo de ecosistema).

:::

::: {.notes}
<!-- en-source: auto-generated speaker notes, do not edit -->
3. Arrange grid cells in ascending order based on their area (smaller first). Calculate accumulated sum of area per cell (‘cumulative area’).
4. Calculate ‘cumulative proportion’ by dividing ‘cumulative area’ by ‘total area’ (cumulative proportion takes values between 0 and 1).
5. Calculate AOO by counting the number of cells with a ‘cumulative proportion’ greater than 0.01 (i.e. exclude cells that in combination account for up to 1% of the total mapped extent of the ecosystem type).
:::

## Cálculo de AOO (directo)

También existe un atributo para calcular el AOO directamente llamado `.aoo`

::: {.notes}
<!-- en-source: auto-generated speaker notes, do not edit -->
**AOO calculation (direct)**

There is also an attribute for calculating AOO directly called `.aoo`
:::

In [30]:
#| echo: true
aoo_direct_calculation = ecosystems.filter(ecosystem_code).aoo
aoo_direct_calculation

4

Asegúrate de que el cálculo directo coincida con los cálculos detallados.

::: {.notes}
<!-- en-source: auto-generated speaker notes, do not edit -->
Make sure the direct calculation matches the detailed calculations.
:::

In [31]:
#| echo: true
if aoo == aoo_direct_calculation:
    print('AOO calculation matches')

AOO calculation matches

## Escribir datos en la nube para su uso posterior

Exportar archivos de datos a Google Cloud Storage para su uso posterior

::: {.callout-tip}
## Región del bucket de Cloud Storage

Al crear un bucket de GCS, elija una región dentro del nivel gratuito: **us-east1**, **us-west1** o **us-central1**. Los buckets en otras regiones generarán cargos de almacenamiento y de red. Consulte [GCP Free Tier](https://cloud.google.com/free/docs/free-cloud-features#storage) para más detalles.
:::

::: {.notes}
<!-- en-source: auto-generated speaker notes, do not edit -->
**Write data to the cloud for later use**

Export data files to Google Cloud Storage for later use

**Cloud Storage Bucket Region**

When creating a GCS bucket, choose a region in the free tier: **us-east1**, **us-west1**, or **us-central1**. Buckets in other regions will incur storage and network charges. See [GCP Free Tier](https://cloud.google.com/free/docs/free-cloud-features#storage) for details.
:::

In [33]:
#| echo: true
gcs_bucket = 'rle-tyler-rle-cogs'

ecosystems.to_parquet(f'gs://{gcs_bucket}/ruritania/ecosystems.parquet')
aoo_grid.to_parquet(f'gs://{gcs_bucket}/ruritania/aoo_grid.parquet')

# Flujo de Trabajo de Publicación Científica y Técnica

Vea las instrucciones en: https://github.com/rle-assessment

::: {.notes}
<!-- en-source: auto-generated speaker notes, do not edit -->
**Scientific & Technical Publishing Workflow**

See instructions at: https://github.com/rle-assessment
:::

## Configurando Su Infraestructura {background-color="white" style="color: black;"}

```{mermaid}
flowchart LR
    subgraph GitHub
        subgraph AssessmentTemplate
            T(["`**Assessment Template**<br/>***TEMPLATE-rle-assessment***`"])
        end
        style AssessmentTemplate stroke:#ffff00,stroke-width:3px
        subgraph AssessmentRepo
            R(["`**Assessment Repo**<br/>***--gh-repo-name***<br/>***Step 2*** Create GitHub Pages Environment<br/>***Step 3*** Add 'main' as Deployment Branch<br/>***Step 4*** Customize project config<br/>***Step 5** Customize _quarto.yml`"])
        end
        style AssessmentRepo stroke:#ffff00,stroke-width:3px
    end
    style GitHub stroke:#ffcc00,stroke-width:3px

    subgraph GCP["**GCP Project**"]
        P["`**Project Config**<br/>***Step 6*** Create/Use project --gcp-project-id<br/>***Step 7***Ensure Owner permissions<br/>***Step 8*** Enable APIs<br/>***Step 11*** Create service account*`"]
        WIP[["Workload Identity Pool<br/>*github-pool*<br/>***Step 9*** Create WIP"]]
        Bucket["Storage buckets"]
    end
    style GCP stroke:#ffcc00,stroke-width:3px
    
    GEE(["Google Earth Engine"])
    T -- ***Step 1*** Create GitHub Repository --> R
    WIP -- ***Step 10*** Create OIDC Provider --> R
    GCP <-- ***Step 12*** Grant IAM Roles --> GEE
    P <-- ***Step 13*** Bind Repository to Service Account--> R
    P <-- ***Step 14*** Grant Token Creator Role --> R
    GCP <-- ***Step 15*** Register Project with Earth Engine --> GEE

    subgraph DevEnvironment
        RClone(["`Assessment Repo (clone)<br/>***--gh-repo-name***<br/>*Step 20 Install Packages*`"])
    end
    style DevEnvironment stroke:#ffcc00,stroke-width:3px

    R -- Step 19 Clone Repository --> RClone


```

::: {.notes}
<!-- en-source: auto-generated speaker notes, do not edit -->
**Configuring Your Infrastructure**
:::